#!H:\release167\NEU\xampp\php\.\php.exe
<?php
/**
 * Get the Compatibility info from PHP CLI
 *
 * PHP versions 4 and 5
 *
 * @category PHP
 * @package  PHP_CompatInfo
 * @author   Davey Shafik <davey@php.net>
 * @license  http://www.php.net/license/3_01.txt  PHP License 3.01
 * @version  CVS: $Id: pci.php,v 1.2 2007/11/15 18:22:40 farell Exp $
 * @link     http://pear.php.net/package/PHP_CompatInfo
 * @access   public
 */

require_once 'PHP/CompatInfo/Cli.php';

$cli = new PHP_CompatInfo_Cli();
$cli->run();

?>